spring:
  application:
    name: itmo-masters-programming-lab-3
  datasource:
    url: jdbc:sqlite:transcoder.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
