name: API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
 test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Images
        run: |
          cd server
          docker build -t server:latest .
          cd ../frontend
          docker build -t frontend:latest .

      - name: Run frontend app
        run: |
          docker run -d --network=host --name frontend -p 3000:3000 frontend:latest

      - name: Run Server in Docker
        run: |
            docker run -d --name server --network=host -v $(pwd)/uploads:/app/uploads -v $(pwd)/transcodes:/app/transcodes -v $(pwd)/db:/app/db -p 8080:8080 server:latest
            
            echo "Waiting for server to start..."
            for i in {1..10}; do
              if nc -z localhost 8080; then
                echo "Server is up."
                break
              else
                echo "Waiting... $i"
                sleep 5
              fi
            done

      - name: Run Tests
        run: |
          docker exec frontend npx playwright test