name: API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
 test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Start Services
        run: |
          docker-compose up --build -d
          echo "Waiting for services to start..."
          sleep 10 # Adjust the sleep time as needed
      
      - name: Install Playwright in Frontend Container
        run: |
          docker-compose exec -T frontend npx playwright install

      - name: Install Playwright dependencies for browser simulation
        run: |
          docker-compose exec -T frontend npx playwright install-deps  

      - name: Run Tests
        run: |
          docker-compose exec -T frontend npx playwright test